apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-acl-web-interface
  labels:
    app: golang-acl-web
spec:  
  selector:
    matchLabels:
      app: golang-acl-web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-acl-web
    spec:
      containers:
        - name: nr-golang-acl
          image: nr-golang-acl:1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081